packaging_format = 2

id = "libretranslate"
name = "LibreTranslate"
description.en = "Open Source Machine Translation API"
description.fr = "API de traduction automatique Open Source"

version = "1.6.1~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://libretranslate.com/"
demo = "https://libretranslate.com/"
admindoc = "https://libretranslate.com/docs/"
code = "https://github.com/LibreTranslate/LibreTranslate"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3, python3-venv"
