packaging_format = 2

id = "libretranslate"
name = "LibreTranslate"
description.en = "Translate text and files between different languages"
description.fr = "Traduisez du textes et des fichiers entre différentes langues"

version = "1.7.3~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://libretranslate.com/"
demo = "https://libretranslate.com/"
admindoc = "https://libretranslate.com/docs/"
code = "https://github.com/LibreTranslate/LibreTranslate"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = true

disk = "2G"
ram.build = "300M"
ram.runtime = "250M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.used_languages]
    ask.en = "Which languages do you plan to use?"
    help.en = "Set every languages acronym separeted with a coma (e.g. en,fr,es,sv,nl)"
    type = "string"
    default = "en,fr,es,sv"
    optional = true
 
    [install.cuda]
    ask.en = "Do you have a gpu or want to run LibreTranslate with the cpu?"
    help.en = "Cuda installations are way bigger and run only on AVX-enabled CPU so use them only if your system supports it"
    type = "select"
    choices = ["cuda", "cpu"]
    default = "cpu"


[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/LibreTranslate/LibreTranslate/archive/refs/tags/v1.7.3.tar.gz"
        sha256 = "74bdfdb54e97306763d8bc25f92dc68c0a262ad91f522feafb98c1ffa6426e51"
        in_subdir = true

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "models" ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3, python3-venv, python3-pip, python3-dev, build-essential, libssl-dev, libffi-dev, python3-setuptools, libicu-dev, python3-icu"
